apiVersion : v1
kind: Namespace
metadata:
  name: unitaire

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-unitaire
  namespace: unitaire
  labels:
    app: GC.WebReact
    tier: web
    env: unitaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: GC.WebReact
      tier: web
      env: unitaire
  template:
    metadata:
      labels:
        app: GC.WebReact
        tier: web
        env: unitaire
    spec:
      containers:
        - name: webapp-unitaire
          image: gabmo/gc.webreact:1
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: secret-unitaire
                  key: connectionString_Default
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment-unitaire
  namespace: unitaire
  labels:
    app: GC.WebReact
    tier: database
    env: unitaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: GC.WebReact
      tier: database
      env: unitaire
  template:
    metadata:
      labels:
        app: GC.WebReact
        tier: database
        env: unitaire
    spec:
      containers:
        - name: sqlserver-unitaire
          image: mcr.microsoft.com/mssql/server:2019-latest
          volumeMounts:
          - name: unitaire-donnees
            mountPath: /var/opt/mssql/data
      volumes:
        - name: unitaire-donnees
          persistentVolumeClaim:
            claimName: unitaire-pvc
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              valueFrom:
                configMapKeyRef:
                  name: configmap-unitaire
                  key: MSSQL_PID
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-unitaire
                  key: MSSQL_SA_PASSWORD
          resources:
            requests:
              cpu: 0.5
              memory: 2Gi
            limits:
              cpu: 1
              memory: 3Gi